katharsis:
  resourcePackage: io.katharsis.domain
  domainName: http://localhost:9090/ipfms
  pathPrefix: /api

server:
  context-path: /ipfms
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://sql3.freemysqlhosting.net
    name: sql3201579
    username: sql3201579
    password: 9Ez82627Ve
    driver-class-name: com.mysql.jdbc.Driver