katharsis:
  resourcePackage: io.katharsis.domain
  domainName: http://localhost:9090
  pathPrefix: /api
  jpa:
    enabled: false

server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost/
    username: sadboys
    password: sadboys
    driver-class-name: com.mysql.jdbc.Driver