katharsis:
  resourcePackage: io.katharsis.domain
  domainName: http://localhost:9090/ipfms
  pathPrefix: /api

server:
  context-path: /ipfms
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    name: recordr
    username: sadboys
    password: sadboys
    driver-class-name: com.mysql.jdbc.Driver